<?php

use Magento\Framework\App\Action\Action;

$dataHelper = $this->helper('MGS\AjaxCart\Helper\Data');

$viewMode = 'grid';
if ($this->getBlockData('mode') == 'masonry.phtml') {
	$image = 'category_page_grid-1';
} else {
	$image = 'category_page_grid';
}
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$_product = $this->getLoadProduct();
$_productNameStripped = $block->stripTags($_product->getName(), null, true);
$productImage = $block->getImage($_product, $image);
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$builderHelper = $this->helper('MGS\Fbuilder\Helper\Data');
$hideName = $this->getBlockData('hide_name');
$hideReview = $this->getBlockData('hide_review');
$hidePrice = $this->getBlockData('hide_price');
$hideAddCart = $this->getBlockData('hide_addcart');
$hideAddWishlist = $this->getBlockData('hide_addwishlist');
$hideAddCompare = $this->getBlockData('hide_addcompare');
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$htmlStructure = $builderHelper->getStoreConfig('fbuilder/html_structure/product_grid');
$effect = $themeSettingConfig->getStoreConfig('themesettings/category/product_hover_effect');

$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$themeHelperImage = $this->helper('MGS\ThemeSettings\Helper\Image');
$hoverChange = $themeSettingConfig->getStoreConfig('themesettings/catalog/hover_change');
$lazyLoad = $themeSettingConfig->getStoreConfig('themesettings/general/lazy_load');
$baseImageLazyload = $this->getViewFileUrl($themeSettingConfig->getPathImageLazyLoad());
?>
<div class="product-item-info" data-container="product-grid">
	<?php echo $themeSettingConfig->getProductLabel($_product); ?>
	<?php if ($effect = 'effect2' || $effect = 'effect4') : ?>
		<div class="action-wishlist">
		</div>
	<?php endif ?>
	    <?php
		$productImage = $block->getImage($_product, $image);
		
		$productImageFirst = $productImage = $_imagehelper->init($_product, $image)->getUrl();
		if ($hoverChange) {
			$productImageHoverFirst = $productImageHover = $_imagehelper->init($_product, 'product_base_image')->getUrl();
		}
		?>
		<div class="product-top">
			<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
				<?php $imgAlt = $_product->getName(); ?>
				<span class="product-image-container">
					<span class="parent_lazy product-image-wrapper" style="padding-bottom: <?php /* @escapeNotVerified */ echo ($themeHelperImage->getRatio() * 100); ?>%;">
						<?php 
							if($lazyLoad) {
								$productImageFirst = $baseImageLazyload;
							}
						?>
						<img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo <?php if($lazyLoad): ?>lazy <?php endif; ?>" data-src="<?php echo $productImage ?>" />
						<?php if ($hoverChange) : ?>

							<?php if (basename($_product->getData('base_image')) !=  'no_selection') : ?>
								
								<?php if (basename($_product->getData('base_image')) != basename($_product->getData('small_image'))) : ?>
									<img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt ?>" class="img-fluid img-hover-show lazy" data-src="<?php echo $productImageHover ?>" />
								<?php endif ?>
							<?php endif ?>
						<?php endif ?>
					</span>
				</span>
			</a>
			<?php if(($hideAddCart!=1) || ($hideAddWishlist!=1) ||($hideAddCompare!=1)): ?>
				<div class="product-item-inner">
					<div class="product actions product-item-actions">
						<?php if($hideAddCart!=1): ?>
							<div class="actions-primary">
								<?php if ($_product->isSaleable()): ?>
									<?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form id="tocart<?php echo $_product->getId() ?>" data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
										<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
										<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
										<?php if($this->getIsAjax()): ?>
											<?php 
												$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
												$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
											?>
											<input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
											<button type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" onclick="ajaxCart('tocart<?php echo $_product->getId() ?>')" class="action tocart primary">
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										<?php else: ?>
											<?= $block->getBlockHtml('formkey') ?>
											<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										<?php endif ?>
										
									</form>
								<?php else: ?>
									<?php if ($_product->isAvailable()): ?>
										<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						<?php endif ?>
						
						<?php if(($hideAddWishlist!=1) ||($hideAddCompare!=1)): ?>
							<div data-role="add-to-links" class="actions-secondary">
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && ($hideAddWishlist!=1)): ?>
									<a href="#" class="action towishlist" title="<?= __('Add to Wish List') ?>" aria-label="<?= __('Save') ?>" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' data-action="add-to-wishlist" role="button">
										<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
									</a>
								<?php endif; ?>
								<?php if($hideAddCompare!=1): ?>
									<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
									<a href="#" class="action tocompare" title="<?= $block->escapeHtml(__('Compare')) ?>" aria-label="<?= $block->escapeHtml(__('Compare')) ?>" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product) ?>' role="button">
										<span><?= /* @escapeNotVerified */ __('Compare') ?></span>
									</a>
								<?php endif ?>
							</div>
						<?php endif ?>
					</div>
				</div>
			<?php endif ?>
		</div>
		<div class="product details product-item-details">
			<?php
				$cateLink = $themeSettingConfig->getCate($_product);
			?>
			<?php if($cateLink):?>
				<div class="product-cate">
					<?php echo $cateLink; ?>
				</div>
			<?php endif ?>
			<?php if($hideName!=1): ?>
				<strong class="product name product-item-name">
					<a class="product-item-link"
					   href="<?= $_product->getProductUrl() ?>">
						<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
					</a>
				</strong>
			<?php endif ?>
			<?php /* if(!$hideReview): ?>
				<?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
			<?php endif */ ?>

		<?php if ($hidePrice != 1) : ?>
			<?= $block->getProductPrice($_product) ?>
		<?php endif ?>

		<?= $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

		<?php //echo $block->getProductDetailsHtml($_product) 
		?>

	</div>
</div>

<script type="text/javascript">
	require([
		'jquery'
	], function(jQuery) {
		(function($) {
			<?php if ($effect = 'effect2' || $effect = 'effect4' || $effect = 'effect8') : ?>
				$(document).ready(function() {
					$(".products-grid.effect2 .product-items .product-item .product-item-info, .products-grid.effect2 .items .product-item .product-item-info").each(function() {
						$(this).find(' .product-item-inner > .product-item-actions > .actions-secondary > .action.towishlist').appendTo($(this).find('.action-wishlist'));
					});
					$(".products-grid.effect4 .product-items .product-item .product-item-info, .products-grid.effect4 .items .product-item .product-item-info").each(function() {
						$(this).find(' .product-item-inner > .product-item-actions > .actions-secondary > .action.towishlist').appendTo($(this).find(' > .action-wishlist'));
					});
					$(".products-grid.effect4 .product-items .product-item .product-item-info, .products-grid.effect4 .items .product-item .product-item-info").each(function() {
						$(this).find(' .product-item-inner > .product-item-actions > .actions-secondary > .action.towishlist').appendTo($(this).find(' > .action-wishlist'));
					});
					$(".products-grid.effect8 .product-items .product-item .product-item-info, .products-grid.effect8 .items .product-item .product-item-info").each(function() {
						$(this).find(' .product-item-inner > .product-item-actions > .actions-secondary > .action.towishlist').appendTo($(this).find(' > .action-wishlist'));
					});
				});
			<?php endif; ?>
		})(jQuery);
	});
</script>